### PR TITLE
feat(bzlmod): Add a gazelle example

### PR DESCRIPTION
**Pull request by aignas**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

There is no example on the `gazelle` setup with `bzlmod`.

Issue Number: #965

## What is the new behavior?

This is the example.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

Depends on #966, #967, #968.

### CODE REVIEW

**Comment by aignas** [comment]
Now also depends on #970

**Comment by chrislovecnm** [comment]
@aignas I was talking with @alexeagle, and he mentioned that we should only support one example.  In the README.md we make a reference to the commit that contains the pre bzmod example. Thoughts?

**Comment by alexeagle** [comment]
No I think the rules repo needs examples for WORKSPACE and MODULE.bazel for a couple years while users are migrating. My comment was about only maintaining one tutorial.

**Comment by chrislovecnm** [comment]
@alexeagle, thanks for the clarification!

**Comment by aignas** [comment]
This is getting stale, so I'll close this in favour of something else in the somewhat near future.

**Pull request closed without merging**
