### PR TITLE
Support "+" in package versions.

### PR DESCRIPTION
**Pull request by calder**
#77: Properly escape "+" in package version strings.

### CODE REVIEW

**Comment by calder** [comment]
@duggelz: Thanks for the review! Tiny update needs reapproval.

**Comment by calder** [comment]
@duggelz: Thanks for the re-review! I still see "Verify Pull Request — Waiting for a project member to verify this pull request." Do you need to merge this?

**Comment by duggelz** [comment]
I think @mattmoor needs to press a button that I don't have permission to press.

**Comment by mattmoor** [comment]
@duggelz done

**Comment by mattmoor** [comment]
Ah, I need to update the branch protection on this repo.

**Comment by calder** [comment]
Thanks @mattmoor and @duggelz! Does someone need to press the "merge" button now? :-)

**Comment by calder** [comment]
Thanks @duggelz!

**Pull request merged**
