### PR TITLE
exec_compatible_with -> target_compatible_with #704

### PR DESCRIPTION
**Pull request by molar**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ x ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #704 

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information
Not sure if people are relying on the exec_compatible_with also being set.

### CODE REVIEW

**Comment by UebelAndre** [comment]
cc @groodt would you be able to take a look at this in the near future?

**Comment by groodt** [comment]
Will take a look this weekend @UebelAndre

**Comment by UebelAndre** [comment]
@groodt friendly ping 😄

**Review by groodt — APPROVED** [review]
LGTM

**Pull request merged**
