### PR TITLE
Ignore `__pycache__` contents and `*.pyc` files in external dependencies

### PR DESCRIPTION
**Pull request by UebelAndre**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Does not include precompiled binaries, eg. `.par` files. See [CONTRIBUTING.md](https://github.com/bazelbuild/rules_python/blob/master/CONTRIBUTING.md) for info
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

I noticed in some of my builds were getting a bunch of unexpected cache misses and found that some pypi dependencies were including some `__pycache__` contents and left-over `*.pyc` files. I don't believe these are needed or should ever be used by the Bazel rules.

Issue Number: N/A

## What is the new behavior?
This PR prevents these files from being included in the `pip_parse` and `pip_install` generated `py_library` targets.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mattem — APPROVED** [review]

**Comment by mattem** [comment]
Hm, this only excludes it from `data`, I'm finding `__pycache__` files in `srcs`

**Comment by UebelAndre** [comment]
I'm on mobile now but I think it'd make sense to exclude them from `srcs` as well. If you wanted to push that change to this branch.

**Comment by mattem** [comment]
Doesn't look like I have permission to push, these were my changes:

```
diff --git a/python/pip_install/extract_wheels/lib/bazel.py b/python/pip_install/extract_wheels/lib/bazel.py
index d498581..6402d8f 100644
--- a/python/pip_install/extract_wheels/lib/bazel.py
+++ b/python/pip_install/extract_wheels/lib/bazel.py
@@ -103,6 +103,7 @@ def generate_build_file_contents(
     """

     data_exclude = [
+        "*dist-info/RECORD",
         "*.whl",
         "**/__pycache__/**",
         "**/*.py",
@@ -137,7 +138,7 @@ def generate_build_file_contents(

         py_library(
             name = "{name}",
-            srcs = glob(["**/*.py"], exclude=["{entry_point_prefix}*.py"], allow_empty = True),
+            srcs = glob(["**/*.py"], exclude=["{entry_point_prefix}*.py", "**/__pycache__/**"], allow_empty = True),
             data = glob(["**/*"], exclude={data_exclude}),
             # This makes this directory a top-level in the python import
             # search path for anything that depends on this.
```

**Comment by UebelAndre** [comment]
> Doesn't look like I have permission to push, these were my changes:

@mattem Ah, I thought you were a maintainer here, makes sense then.

I picked up the only the additional exclude for `__pycache__`. I'm wondering why `*dist-info/RECORD` would be ignored and not all of `*dist-info/**`. Could you explain the reasoning there?

**Review by thundergolfer — APPROVED** [review]
Looks correct to me.

**Comment by UebelAndre** [comment]
> > Doesn't look like I have permission to push, these were my changes:
> 
> @mattem Ah, I thought you were a maintainer here, makes sense then.
> 
> I picked up the only the additional exclude for `__pycache__`. I'm wondering why `*dist-info/RECORD` would be ignored and not all of `*dist-info/**`. Could you explain the reasoning there?

Would still like to hear @mattem's response to this if you don't mind 😄

**Pull request merged**
