### PR TITLE
Allow any capitalization in requirement names.

### PR DESCRIPTION
**Pull request by mattmoor**
Quoting @duggelz

> From PEP 508 it appears that you can register packages with any capitalization, and install them with any capitalization, even if it's different. I.e. you can register package 'MyPackage' and install it with mypackage, MYPACKAGE, or even mYpAcKaGe.
>
> That is not an ideal spec, but is it the spec, and the tools implement it, so we should to.

Thanks to @justinwb for the original PR.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by mattmoor** [comment]
@damienmg Any idea why the bot doesn't recognize my super powers? :D

**Comment by mattmoor** [comment]
test this please

**Comment by damienmg** [comment]
(seems like it did :p)

**Pull request merged**
