### PR TITLE
always lowercase requirements dictionary keys

### PR DESCRIPTION
**Pull request by justinwp**
not sure if this has any other ramifications

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by justinwp** [comment]
I signed it!

**Comment by duggelz** [comment]
From [PEP 508](https://www.python.org/dev/peps/pep-0508/) it appears that you can register packages with any capitalization, and install them with any capitalization, even if it's different.  I.e. you can register package 'MyPackage' and install it with `mypackage`, `MYPACKAGE`, or even `mYpAcKaGe`.

That is not an ideal spec, but is it the spec, and the tools implement it, so we should to.

**Comment by duggelz** [comment]
Patch looks ok to me, but we'll want to add a test (package `PyYAML` seems a good choice), and then an admin (@mattmoor) will need to rebuild the piptool.par file.

**Comment by duggelz** [comment]
Sorry, that was actually a "yes this seems like a good patch", not a "no".  We should accept `requirements("PyYAML")` and normalize it to "pyyaml" like pip does.

**Comment by duggelz** [comment]
I guess the real test would be if some library had `requirements("PyYAML")` and some other library had `requirements("pyyaml")`.  We would want to realize that those are actually the same thing.

**Comment by mattmoor** [comment]
This LGTM, not sure why @justinwp closed/deleted, but I'll recreate it with an updated PAR.  thanks Justin.

**Pull request closed without merging**
