### PR TITLE
build(deps): Update the pip_install dependencies

### LINKED ISSUE #1821: Update internal pip version to 23.3+
# 🚀 feature request

Update internal pip version to 23.3+
The current internal pip version is specified as 23.2 https://github.com/bazelbuild/rules_python/blob/c5c03b2477dd1ce0c06c9dc60bf816995f222bcf/python/pip_install/repositories.bzl#L64

### Relevant Rules
pip.parse
compile_pip_requirements()

### Description

The new http-v2 caching feature was introduced in pip 23.3. This feature separates out headers the body when caching responses from package servers. This fixes a performance issue that causes cached responses to be loaded and fully deserialized multiple times from disk during a single run of compile_pip_requirements / pip-compile. This is an issue for wheels that are GB in size.

### Describe the solution you'd like

Update internal pip version to 23.3+ or maybe add a way for the user to specify the desired pip version when specifying pip.parse() or compile_pip_requirements().

### Describe alternatives you've considered

Write a py_binary depending on the pip version I need and then run pip-compile inside that py_binary.

### PR DESCRIPTION
**Pull request by JulesDT**
Bumps:
* importlib_metadata: 6.8.0 -> 7.1.0
* more_itertools: 10.1.0 -> 10.2.0
* packaging: 23.1 -> 24.0
* pep517: 0.13.0 -> 0.13.1
* pip: 23.2.1 -> 24.0
* pyproject_hooks: 1.0.0 -> 1.1.0
* setuptools: 68.1.2 -> 70.0.0
* wheel: 0.41.2 -> 0.43.0
* zipp: 3.16.2 -> 3.18.2

Fixes #1821

### CODE REVIEW

**Comment by aignas** [comment]
Thanks, this is looking good! Could you please add a changelog entry?

**Comment by JulesDT** [comment]
Changelog updated, thank you :)

**Review by aignas — APPROVED** [review]
LGTM, thank you!

**Comment by aignas** [comment]
Please rebase. It seems that some requirement tests are failing (the one in docs/sphinxdocs) in particular.

**Comment by JulesDT** [comment]
Indeed thank you, I just rebased and updated the sphinx doc in the right commit! Looks like the CI is passing now :)

**Pull request merged**
