### PR TITLE
fix compile_pip_requirements on windows

### PR DESCRIPTION
**Pull request by jheaff1**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

PR #529 updated `click` to a version which depends on `colorama` on Windows. This broke the generation of a `requirements.txt` lock file using the `compile_pip_requirements` rule on windows. 
Issue Number: #529 

## What is the new behavior?
The generation of a `requirements.txt` lock file using the `compile_pip_requirements` rule on windows now works

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by UebelAndre** [comment]
Now that `rules_python` runs tests on Windows runners in CI (https://github.com/bazelbuild/rules_python/pull/585), I'm surprised this wasn't caught then. I thought `compile_pip_requirements` was run as part of the `@rules_python//examples:pip_install_example` integration test:
https://github.com/bazelbuild/rules_python/blob/0.6.0/examples/pip_install/BUILD#L69-L73

**Comment by jheaff1** [comment]
> Now that `rules_python` runs tests on Windows runners in CI (#585), I'm surprised this wasn't caught then. I thought `compile_pip_requirements` was run as part of the `@rules_python//examples:pip_install_example` integration test: https://github.com/bazelbuild/rules_python/blob/0.6.0/examples/pip_install/BUILD#L69-L73
> 
> Do you know why this might not be caught by that test and if something can be done to improve the test coverage for the rule?

It seems that `test_runner.py` did not detect failing tests. Please see #597

**Review by UebelAndre — APPROVED** [review]
> It seems that `test_runner.py` did not detect failing tests. Please see #597

Most unfortunate. Though, having tested these changes on both macos and windows, I think they're good. Both platforms work and I think it'd be good to have this change while the test runner issues are fixed separately.

Though, I'm not a maintainer so my opinion has little value here 😅

**Review by alexeagle — APPROVED** [review]
thanks!

**Pull request merged**
