### PR TITLE
Fix documentation bug

### PR DESCRIPTION
**Pull request by mattmoor**
Fixes: https://github.com/bazelbuild/rules_python/issues/7

### CODE REVIEW

**Comment by mattmoor** [comment]
@damienmg Again, Bazel CI seems hosed?

**Comment by damienmg** [comment]
All slaves are down... Trying to restart the server.

**Comment by damienmg** [comment]
Jenkins retest this please

**Comment by damienmg** [comment]
Jenkins: can you be so kind to retest this please?

**Pull request merged**
