### PR TITLE
docs: Add starlark directive to code snippet

### PR DESCRIPTION
**Pull request by blorente**
A very minor cleaup change.

### CODE REVIEW

**Review by chrislovecnm — APPROVED** [review]
LGTM - I think we have a flake on CI

**Comment by chrislovecnm** [comment]
@blorente can you push a null update to get CI to run again?

**Review by chrislovecnm — APPROVED** [review]
LGTM

**Comment by blorente** [comment]
@chrislovecnm Sure thing :D

**Comment by chrislovecnm** [comment]
@f0rmiga, @alexeagle, @rickeylev can we merge?

**Review by rickeylev — APPROVED** [review]

**Pull request merged**
