### PR TITLE
Revert "pip_compile: remove external/workspace_name prefix from gener…

### LINKED ISSUE #766: Local relative requirements compile fails under 0.10.0+
# 🐞 bug report

### Affected Rule

compile_pip_requirements

### Is this a regression?

Yes. Works in 0.9.0, broken in 0.10.0+

### Description

Setup is as here: https://github.com/bazelbuild/rules_python/issues/366

Under 0.10.0 and above, relative requirements fail due to not being able to resolve the file path.

Bug was introduced in aef17ad72919d184e5edb7abf61509eb78e57eda

Issue is the removal of `os.chdir`:

https://github.com/bazelbuild/rules_python/blob/dae610b9cad8e355eec388025807bbedc244c5de/python/pip_install/pip_compile.py#L44-L52

Became:

https://github.com/bazelbuild/rules_python/blob/aef17ad72919d184e5edb7abf61509eb78e57eda/python/pip_install/pip_compile.py#L49-L57

## 🔬 Minimal Reproduction

See https://github.com/bazelbuild/rules_python/issues/366

## 🔥 Exception or Error

<pre><code>

WARNING:pip._internal.req.constructors:Requirement 'deps/some_name/some_name-1.2.3-py3-none-any.whl' looks like a filename, but the file does not exist
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.3 LTS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 5.0.0
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.10.2
  </code>
</pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by alexeagle**
…ated requirements.txt (#690)"

This reverts commit aef17ad72919d184e5edb7abf61509eb78e57eda.

Fixes #766

### CODE REVIEW

**Review by hrfuller — APPROVED** [review]

**Comment by hrfuller** [comment]
I know we decided this kind of drive-by change doesn't follow our principles for evolving the project, and makes the code that much harder to read, but just curious were there any known breakages caused by this?

**Review by groodt — APPROVED** [review]
LGTM

**Review by Ghjkvvgj — COMMENTED** [review]
Y

**Review by Ghjkvvgj — COMMENTED** [review]
Gil

**Pull request merged**
