### PR TITLE
Merge rules python external

### PR DESCRIPTION
**Pull request by alexeagle**
This is the beginning of making that the canonical way to get dependencies, replacing the pip features in this repo.

Our plan is in multiple steps:

- (this PR) bring in the repo to a subdirectory, preserving git history and contributors
- clean up the code, remove mypy, get it functional in that subdirectory
- add an example/integration test proving that it works
- cut a patch release and get some users to test it out
- communicate our deprecation plan to rules_python users
- BIG SWITCH: move the rules_python_external implementation to the root, make a legacy/ directory for current impl
- fill in any missing docstrings and include new rules in stardoc
- cut a breaking release (a minor, since semver starting with 0. states that minors are breaking)
- help users switch over
- in a later breaking release, actually remove the old implementation

### CODE REVIEW

**Comment by dillon-giacoppo** [comment]
@googlebot I consent.

**Comment by alexeagle** [comment]
Note, buildkite failure is because it treats linter warnings as fatal. My recommendation is to make the new subdirectory lint-clean in a followup PR, but we could add a commit here to make it green if maintainers prefer.

**Comment by thundergolfer** [comment]
@googlebot I consent.

**Comment by alexeagle** [comment]
gergelyfabian has signed the CLA as he authored #315 
remaining authors of commits merged here have only one commit each on rules_python_external, mostly trivial changes.

**Comment by groodt** [comment]
@googlebot I consent.

**Comment by groodt** [comment]
> remaining authors of commits merged here have only one commit each on rules_python_external, mostly trivial changes.

Not sure if it makes it any easier if everyone signs the CLA or not, but maybe mentioning them will help put this on their radar.

cc
@spietras 
@gergelyfabian 
@kevingessner
@chickenandpork
@benjamin-fleischmann
@JoshuaCrestone

**Comment by chickenandpork** [comment]
(CLA done)

**Comment by JoshuaCrestone** [comment]
(CLA done)

**Comment by gergelyfabian** [comment]
(CLA done)

JoshuaCrestone <notifications@github.com> ezt írta (időpont: 2020. aug.
21., P 2:57):

**Comment by gergelyfabian** [comment]
@googlebot I consent.

**Comment by spietras** [comment]
@googlebot I consent.

**Comment by benjamin-fleischmann** [comment]
@googlebot I consent.

**Comment by alexeagle** [comment]
@chickenandpork could you also reply with the `@googlebot I consent.` text? I think this is the last one causing CLA status to be red

**Comment by chickenandpork** [comment]
@googlebot I consent.

**Comment by chickenandpork** [comment]
I'm not sure if this PR needs some manual re-kick to recheck CLAs.  If you want to bisect the issue or carve off some delta by splitting this PR or pulling aside us minimal-impacters, @-tag me, happy to come back and consent to another merge

**Comment by alexeagle** [comment]
As long as we have documented the consent, we aren't required to make the check turn green. This is ready to merge I think, just requires an admin to click the button

**Review by thundergolfer — APPROVED** [review]

**Pull request merged**
