### PR TITLE
Upgrade to setuptools==44.0.0

### PR DESCRIPTION
**Pull request by XingChenKolmostar**
This allows new features in setuptools, like find_namespace_packages.

### CODE REVIEW

**Comment by XingChenKolmostar** [comment]
@googlebot I signed it!

**Comment by lberki** [comment]
Where do these binaries come from? I'm reluctant to merge some random binary blob.

**Comment by XingChenKolmostar** [comment]
https://github.com/bazelbuild/rules_python/blob/master/update_tools.sh

Generated them. I used the default (docker).


lberki <notifications@github.com> 于 2020年3月3日周二 00:25写道：

**Comment by lberki** [comment]
Erm, sorry for being somewhat dense. I'll regenerate the binary blobs them and will merge this pull request instead:

https://github.com/bazelbuild/rules_python/pull/286

**Comment by lberki** [comment]
Rebuilt the binaries, checksum matches. Will merge!

**Comment by brandjon** [comment]
Thanks Lukács. For reference we always [regenerate](https://github.com/bazelbuild/rules_python/blob/master/CONTRIBUTING.md#precompiled-tools) the par files before merging.

**Pull request merged**
