### PR TITLE
Fix typo in wheel return type

### PR DESCRIPTION
**Pull request by lfn3**
This causes an error when running from latest main:

```
ERROR: An error occurred during the fetch of repository 'my_deps':
   Traceback (most recent call last):
        File ".../gbobcgvx/external/rules_python/python/pip_install/pip_repository.bzl", line 195, column 13, in _pip_repository_impl
                fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed:  (Traceback (most recent call last):
  File "...\gbobcgvx\external\python3_8_x86_64-pc-windows-msvc\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  
  ...
  
    from python.pip_install.extract_wheels.lib import wheel
  File "...\gbobcgvx\external\rules_python\python\pip_install\extract_wheels\lib\wheel.py", line 28, in <module>
    class Wheel:
  File "...\gbobcgvx\external\rules_python\python\pip_install\extract_wheels\lib\wheel.py", line 55, in Wheel
    def entry_points(self) -> Dict[str, tuple[str, str]]:
TypeError: 'type' object is not subscriptable
```

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Errors when using `pip_parse`.

Issue Number: N/A

## What is the new behavior?
Does not error.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Not sure how to write a test for this, but would appreciate guidance on how to do so.

### CODE REVIEW

**Comment by hrfuller** [comment]
Will ship if you fix the tests.

**Review by thundergolfer — COMMENTED** [review]
Ah yep, while we support Python 3.6 `tuple` as a type-hint won't work. [PEP 585](https://peps.python.org/pep-0585/) has info how we can support `tuple` in 3.7+ with an import. Full support is only in 3.9+. 

You need to import `Tuple` to fix the tests.

**Comment by lfn3** [comment]
🤦 Added the import so it should be fixed now.

**Comment by f0rmiga** [comment]
Superseded by https://github.com/bazelbuild/rules_python/pull/722.

**Pull request closed without merging**
