### PR TITLE
Made version failure message better reflect the issue

### PR DESCRIPTION
**Pull request by jdob**
I ran into a sitation that triggered this failure. I have version 5.0.0 installed, so it was confusing to see a message telling me my version was lower than 0.2.1.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] Other... Please describe:

Error message clarification.

## What is the current behavior?

Issue Number: N/A

I received the following output from a build

<pre><code>
        File "/private/var/tmp/_bazel_jdob/300f9ff46946083ee2e5c32c9a7995b7/external/rules_python/third_party/github.com/bazelbuild/bazel-skyli
b/lib/versions.bzl", line 92, column 17, in _check_bazel_version
                fail("Current Bazel version is lower than 0.2.1; expected at least {}".format(
Error in fail: Current Bazel version is lower than 0.2.1; expected at least 4.0.0
</code></pre>

Running Bazel shows I have a higher version than 0.2.1:

<pre><code>
bazel version
Build label: 5.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:15:55 2022 (1642601755)
Build timestamp: 1642601755
Build timestamp as int: 1642601755
</code></pre>

## What is the new behavior?

The error message indicates that the version cannot be determined, rather than the message reflecting an old version.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by j1ah0ng** [comment]
Did you end up fixing this error? I'm attempting to figure out why the vendored skylib can't determine my Bazel version.

**Comment by aiuto** [comment]
The change seems reasonable, but why is there a private skylib?   https://github.com/bazelbuild/rules_python/issues/667

**Comment by mattem** [comment]
> The change seems reasonable, but why is there a private skylib? #667

Generally rules seem to vendor these so as to not pass on the dependency to users, as it's hard to align versions across the WORKSPACE.

**Review by thundergolfer — APPROVED** [review]

**Comment by thundergolfer** [comment]
@jdob can you sign the Google CLA? It's required for contributors. 

Ref: https://github.com/bazelbuild/rules_python/pull/663/checks?check_run_id=6647738287

**Comment by jdob** [comment]
I have so breathtakingly screwed up this repo in trying to change the author e-mail (which was the actual issue) that I'm just going to kill it off and do it again. It'll be faster than unknotting this.

**Pull request closed without merging**
