### PR TITLE
Update bazel version in versions file

### PR DESCRIPTION
**Pull request by hanneskaeufler**
Bumps the bazel version to be up to date

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by hanneskaeufler** [comment]
Can't really tell what the failing tests is, it passes for me locally

**Comment by groodt** [comment]
The error in buildkite appears to be:
```
ERROR: <builtin>: fetching local_repository rule //external:rules_python.override: java.io.IOException: No WORKSPACE file found in /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/114/execroot/rules_python/_tmp/b45ad76472382f795d1e61dde171a896/_bazel_buildkite-agent/38318e911819c1b3a890d526b9ce4994/external/rules_python.override
--
  | ERROR: No WORKSPACE file found in /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/114/execroot/rules_python/_tmp/b45ad76472382f795d1e61dde171a896/_bazel_buildkite-agent/38318e911819c1b3a890d526b9ce4994/external/rules_python.override
```

I think I'll revert https://github.com/bazelbuild/rules_python/pull/837 so we can do them together once we figure out the issue.

**Comment by groodt** [comment]
Correction, can you please try raise a "revert" PR @hanneskaeufler ? Then I can approve and merge without waiting for other maintainers.

**Comment by hanneskaeufler** [comment]
@groodt  sure, here you go: https://github.com/bazelbuild/rules_python/pull/842

**Comment by groodt** [comment]
@hanneskaeufler You can either repurpose this PR to try and bump everything in a single PR. Or open a new clean PR.

**Comment by hanneskaeufler** [comment]
hm, did the former, but something does indeed seem to be off here. I'm not yet knowledgable about bzlmod to really get a grip on this right now.

**Pull request closed without merging**
