### PR TITLE
Revert "Add option to use "pip download" instead of "pip wheel" to do…

### PR DESCRIPTION
**Pull request by groodt**
…wnload wheels for other platforms (#773)"

This reverts commit 6a43ebd6e4d8a11aaa5c303e7b03c72a136f62a0.

<hr />

Exploring if this PR is causing main to fail. See: https://buildkite.com/bazel/rules-python-python/builds/3242#0182dec5-050b-4fa3-9506-5e606ad0c4e1

Update: Reverting this PR will fix main. I think I should have updated the PR branch before merging because it was a bit old (25 days).

### CODE REVIEW

**Review by f0rmiga — APPROVED** [review]

**Comment by groodt** [comment]
@UebelAndre I prefer to revert, review the fix, merge the fix if good and then revert the revert.

**Comment by UebelAndre** [comment]
@groodt So with https://github.com/bazelbuild/rules_python/pull/809 merged could this now be reverted? Didn't the passing CI on that PR show it addressed the issues this revert was trying to undo?

**Comment by UebelAndre** [comment]
I've created https://github.com/bazelbuild/rules_python/pull/810 to hopefully show the changes in https://github.com/bazelbuild/rules_python/pull/809 address the issues uncovered by the original implementation.

**Comment by groodt** [comment]
@UebelAndre I did similar in https://github.com/bazelbuild/rules_python/pull/811

Can you close #810 so all the context is self-contained?

**Comment by UebelAndre** [comment]
> Can you close #810 so all the context is self-contained?

Sorry, figured it'd be more convenient for me to open it so you could be the reviewer (not needing another `rules_python` maintainer to come around for the approval). The PR is closed.

**Comment by groodt** [comment]
> Sorry, figured it'd be more convenient for me to open it so you could be the reviewer (not needing another rules_python maintainer to come around for the approval). The PR is closed.

No worries. Thanks! I should have been more clear that I intended to do it. I was just unwinding the PRs. The PR should merge shortly and I'll tag a new release in the next few days as well.

**Pull request merged**
