### PR TITLE
fix: generation of toolchain aliases //:defs.bzl file.

### PR DESCRIPTION
**Pull request by oxidase**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

With `common --experimental_enable_bzlmod` option defs.bzl is generated as
```
load("@rules_python~override//python/config_settings:transition.bzl", _py_binary = "py_binary", _py_test = "py_test")
load("@rules_python~override//python:pip.bzl", _compile_pip_requirements = "compile_pip_requirements")
```
and these lines cause a problem at
```
load("@python3_9//:defs.bzl", "interpreter")
```
as
```

ERROR: .../BUILD:25:11: error loading package 'src': at .../external/rules_python~override~python~python3_9/defs.bzl:4:6: Unable to find package for @[unknown repo 'rules_python~override' requested from @rules_python~override~python~python3_9]//python:pip.bzl: The repository '@[unknown repo 'rules_python~override' requested from @rules_python~override~python~python3_9]' could not be resolved: No repository visible as '@rules_python~override' from repository '@rules_python~override~python~python3_9'. and referenced by '...'
```

Issue Number: N/A

## What is the new behavior?

Generated load statements
```
load("@@rules_python~override//python/config_settings:transition.bzl", _py_binary = "py_binary", _py_test = "py_test")
load("@@rules_python~override//python:pip.bzl", _compile_pip_requirements = "compile_pip_requirements")
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by oxidase** [comment]
@hrfuller @rickeylev please could you review the fix?

**Comment by f0rmiga** [comment]
@oxidase could you modify the example for bzlmod to assert this, please?

**Comment by oxidase** [comment]
@f0rmiga added `test_with_transition` to the example. Without the fix running tests fails as
```
cd examples/bzlmod && bazel test //...
ERROR: error loading package under directory '': error loading package '': at .../external/rules_python~override~python~python3_9/defs.bzl:4:6: 
Unable to find package for @[unknown repo 'rules_python~override' requested from @rules_python~override~python~python3_9]//python:pip.bzl: 
The repository '@[unknown repo 'rules_python~override' requested from @rules_python~override~python~python3_9]' 
could not be resolved: No repository visible as '@rules_python~override' from repository '@rules_python~override~python~python3_9'.
```

**Review by f0rmiga — APPROVED** [review]
Awesome, thank you.

**Review by f0rmiga — APPROVED** [review]

**Pull request merged**
