### PR TITLE
Update runfiles lib

### PR DESCRIPTION
**Pull request by fmeum**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

rules_python's runfiles library is affected by https://github.com/bazelbuild/bazel/issues/14336, which has been fixed upstream.

## What is the new behavior?

rules_python's version of the runfiles library contains https://github.com/bazelbuild/bazel/commit/486d153d1981c3f47129f675de20189667667fa7

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Also adds the tests contained in the Bazel repo.

### CODE REVIEW

**Comment by fmeum** [comment]
@alexeagle This is the first commit with changes backported (?) from Bazel. I will start adding the Bzlmod changes as follow-ups.

**Comment by fmeum** [comment]
Is there a canonical way to format Python files? The runfiles library differs from the Bazel Core one in this regard and I would like to stay consistent with the formatting style used in this repo.

**Review by alexeagle — APPROVED** [review]
Thanks! I assume this was already reviewed when it was changed upstream so we are just updating our vendored copy

**Review by rickeylev — APPROVED** [review]

**Comment by fmeum** [comment]
I ran the formatters.

**Comment by alexeagle** [comment]
Thanks!

**Pull request merged**
