### PR TITLE
refactor(gazelle): Move plugin to a separate directory.

### PR DESCRIPTION
**Pull request by aignas**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

@alexeagle requested to split #972 into multiple PRs for easier review, so this is the first part.

Issue Number: #965

## What is the new behavior?

This is in order to make #972 easier to review. This PR is only moving files and addressing a few small review comments made in the initial review of #972. I have also made `alias` targets to make this a non-breaking change from the user point of view in case a release is made before the breaking change of introducing the new `WORKSPACE` is merged.

Work towards #965.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by aignas** [comment]
@f0rmiga, could you please take a look when you have time?

**Comment by alexeagle** [comment]
Well, now I'm a bit confused because we just added "optional" dependencies https://github.com/bazelbuild/rules_python/blob/main/MODULE.bazel#L9-L11
that not all users of rules_python need. Maybe these two are just harmless in a way that rules_go isn't?

**Comment by aignas** [comment]
I somewhat still think that having this refactoring in won't hurt, given that once it is done we can either way - a single `MODULE.bazel` or multiple.

**Review by f0rmiga — APPROVED** [review]
Could you resolve the conflicts, please?

**Pull request merged**
