### PR TITLE
"Skylark" is an outdated name of the language, please use "starlark" …

### PR DESCRIPTION
**Pull request by thundergolfer**
master CI build [is currently failing with](https://buildkite.com/bazel/rules-python-python/builds/834#a478721a-3cda-4b27-903a-abe2d7def4d9): 

```
href="https://github.com/bazelbuild/rules_python/blob/eabd5344d8419eb0077e6be5df948c37a1186202/experimental/python/wheel.bzl#L43">experimental/python/wheel.bzl:43</a>: <a href="https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#skylark-comment">skylark-comment</a>: "Skylark" is an outdated name of the language, please use "starlark" instead.</pre></code>
```

### CODE REVIEW

**Comment by gergelyfabian** [comment]
There is also another build failure, that affects all PRs (including yours):

> Could not find pip-provided dependency: 'googleapis-common-protos[grpc]'

**Comment by thundergolfer** [comment]
@gergelyfabian Yeah I think there's an issue open for that one. I'll tackle that in a separate PR. hopefully get some time soon.

**Comment by gergelyfabian** [comment]
> @gergelyfabian Yeah I think there's an issue open for that one. I'll tackle that in a separate PR. hopefully get some time soon.

Yes, indeed: https://github.com/bazelbuild/rules_python/issues/321. I have proposal for a fix, will send a PR :)

**Comment by gergelyfabian** [comment]
> > @gergelyfabian Yeah I think there's an issue open for that one. I'll tackle that in a separate PR. hopefully get some time soon.
> 
> Yes, indeed: #321. I have proposal for a fix, will send a PR :)

The fix is in #329. Let's merge these two PRs if possible to have builds get fixed :)

**Comment by andyscott** [comment]
This _should_ go green now that #329 has merged.

**Pull request merged**
