### PR TITLE
Update dependencies for compatibility with Bazel 0.6.0

### PR DESCRIPTION
**Pull request by vladmos**

### CODE REVIEW

**Comment by mattmoor** [comment]
@duggelz Does `google/subpar` need this or did your recent change address it?

**Comment by duggelz** [comment]
What was the compatibility issue?  I traced this to a skydoc commit (https://github.com/bazelbuild/skydoc/pull/53/files), then to a protobuf commit (https://github.com/google/protobuf/pull/3495), which seems to be a C++ compilation fix, not obviously related to Bazel 0.6.0.

**Comment by duggelz** [comment]
Answer: `The set constructor for depsets is deprecated and will be removed.`, fixed in https://github.com/bazelbuild/skydoc/pull/52

**Comment by vladmos** [comment]
Yes, that's the compatibility issue I was trying to fix.

**Pull request merged**
