### PR TITLE
Terminology update 'master' to 'main' in DEVELOPING.md

### PR DESCRIPTION
**Pull request by thundergolfer**
Change directly related to #500 

As far as I can see these are the only relevant `master` refs in the codebase.

----

### PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Does not include precompiled binaries, eg. `.par` files. See [CONTRIBUTING.md](https://github.com/bazelbuild/rules_python/blob/master/CONTRIBUTING.md) for info
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by thundergolfer** [comment]
Requesting @hrfuller as I think Alex may be on vacation.

**Comment by thundergolfer** [comment]
:bump: @hrfuller 

Merging this should also trigger CI and we can check it's compatible with our new `main` branch setup.

**Review by alexeagle — APPROVED** [review]

**Comment by thundergolfer** [comment]
@philwo [our scheduled builds are failing](https://buildkite.com/bazel/rules-python-python/builds/1717#893b784b-09f0-4a2a-a4e9-a60378d861fd) due the `main` rename. What do we have to update to fix this?

**Comment by alexeagle** [comment]
@fweikert has an open PR for this already on bazelbuild/continuous-integration repo

**Comment by thundergolfer** [comment]
Is there? I can't see it https://github.com/bazelbuild/continuous-integration/issues?q=is%3Aissue+author%3Afweikert+

**Comment by philwo** [comment]
Should be working again now!

I fixed the "Default branch" setting in Buildkite:
image

And the branch of the "Scheduled builds":
Screen Shot 2021-07-09 at 11 22 31

**Comment by thundergolfer** [comment]
@philwo Thanks mate 🙏

**Pull request merged**
