### PR TITLE
fix: dependency resolver on windows only works when --enable_runfiles and --windows_enable_symlinks is used

### LINKED ISSUE #1431: requirements.update doesn't work on windows when requirements.in in a subpackage
### Affected Rule
The issue is caused by the rule: compile_pip_requirements

### Is this a regression?
Yes this regressed between: https://github.com/bazelbuild/rules_python/compare/0.18.0...0.19.0

### Description
If you have a rule in a sub package (so it contains a directory separator) then on windows you will get an issue where it cannot find file path for requirements.txt.

Note: the slashes are the wrong direction for windows. 

## 🔬 Minimal Reproduction

In 0.25.0 branch of rules_python
<pre><code>
cd .\examples\pip_parse\
REM This works
bazel run requirements.update

mkdir bad
copy .\BUILD.bazel bad
copy .\requirements.in bad
copy .\requirements_lock.txt bad

REM This fails with Error: Could not open file 'bad/requirements_lock.txt': No such file or directory
bazel run //bad:requirements.update

</code></pre>

## 🔥 Exception or Error

<pre><code>

INFO: Running command line: bazel-bin/tools/thirdparty/requirements.update.exe tools/thirdparty/requirements.in tools/thirdparty/requirements.txt None None None //tools/thirdparty:requirements.update --allow-unsafe --no-reuse-hashes
Updating tools/thirdparty/requirements.txt
Traceback (most recent call last):
  File "C:\Users\JAMESC~1\AppData\Local\Temp\Bazel.runfiles_gwh6jf4s\runfiles\rules_python\python\pip_install\tools\dependency_resolver\dependency_resolver.py", line 139, in <module>
    if not os.path.samefile(requirements_txt, requirements_txt_tree):
  File "C:\Users\JAMESC~1\AppData\Local\Temp\Bazel.runfiles_gwh6jf4s\runfiles\python3_10_x86_64-pc-windows-msvc\lib\genericpath.py", line 100, in samefile
    s1 = os.stat(f1)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'tools/thirdparty/requirements.txt'
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
windows 
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 6.2.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 9 18:34:17 2023 (1683657257)
Build timestamp: 1683657257
Build timestamp as int: 1683657257
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.25.0
  </code>
</pre>

**Anything else relevant?**
Same code works fine on macos and WSL.

### LINKED ISSUE #1943: bazel run //:requirements.update writes to stdout instead of updating requirements_lock.txt
# 🐞 bug report

### Affected Rule

Not sure

### Is this a regression?

Not sure

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Command:
```
d:\workdir>bazel run //:requirements.update
INFO: Analyzed target //:requirements.update (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:requirements.update up-to-date:
  bazel-bin/requirements.update.zip
  bazel-bin/requirements.update.exe
INFO: Elapsed time: 79.753s, Critical Path: 78.37s
INFO: 3 processes: 2 internal, 1 local.
INFO: Build completed successfully, 3 total actions
INFO: Running command line: bazel-bin/requirements.update.exe _main/tools/bb/requirements.txt _main/requirements_lock.txt //:requirements.update '--resolver=backtracking' --allow-unsafe --generate-hashes '--requirements-windows=_main/requirements_windows.txt'
Updating requirements_windows.txt
WARNING: --strip-extras is becoming the default in version 8.0.0. To silence this warning, either use --strip-extras to opt into the new default or use --no-strip-extras to retain the existing behavior.
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    bazel run //:requirements.update
#
(snip)
```

MODULE.bazel
```
bazel_dep(name = "rules_python", version = "0.32.2")
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.11",
    is_default = True,
    ignore_root_user_error = True,
)
pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "bb_deps",
    python_version = "3.11",
    # We can use `envsubst in the above
    envsubst = ["PIP_INDEX_URL"],
    # Use the bazel downloader to query the simple API for downloading the sources
    # Note, that we can use envsubst for this value.
    experimental_index_url = "${PIP_INDEX_URL:-https://pypi.org/simple}",
    requirements_lock = "//:requirements_lock.txt",
)
use_repo(pip, "bb_deps")
```

BUILD.bazel
```
load("@gazelle//:def.bzl", "gazelle")
load("@rules_python//python:pip.bzl", "compile_pip_requirements")

# gazelle:prefix company.com/bazel2
gazelle(name = "gazelle")

# This stanza calls a rule that generates targets for managing pip dependencies
# with pip-compile.
compile_pip_requirements(
    name = "requirements",
    timeout = "moderate",
    src = "//tools/bb:requirements.txt",
    requirements_txt = "requirements_lock.txt",
    requirements_windows = "requirements_windows.txt",
)
```

## 🔥 Exception or Error

requirements_lock.txt and requirements_windows.txt are not updated. 

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
7.2.0rc3
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.32.2
  </code>
</pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by ChewyGumball**
`compile_pip_requirements` doesn't work as expected on Windows unless both `--enable_runfiles` and `--windows_enable_symlinks` are used. Both options default to off on Windows because the filesystem on Windows makes setting up the runfiles directories with actual files very slow. This means that anyone on Windows with a default set up has to search around the Github issues to try and figure out why things don't work as advertised.

The `dependency_resolver.py` doesn't inherently require these options, it just had two bugs that prevented it from working.

1. calling pip_compile exits the whole program so it never gets to run the code that should copy the output to the source tree. Things just happen to work on linux because the runfiles are symlinks, and it does not need to copy anything.
2. it assumed the `runfiles` resolved file would be in the runfiles tree, but on Windows, when `--enable_runfiles` is not set, it actually gets resolved to a file in the source tree.

Before:
```sh
bazel run //third_party/python:requirements.update
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 8aa3e832-78ce-4999-912b-c43e7ca3212b
INFO: Analyzed target //third_party/python:requirements.update (129 packages loaded, 9563 targets configured).
INFO: Found 1 target...
Target //third_party/python:requirements.update up-to-date:
  bazel-bin/third_party/python/requirements.update.zip
  bazel-bin/third_party/python/requirements.update.exe
INFO: Elapsed time: 60.964s, Critical Path: 0.77s
INFO: 8 processes: 2 remote cache hit, 6 internal.
INFO: Build completed successfully, 8 total actions
INFO: Running command line: bazel-bin/third_party/python/requirements.update.exe '--src=_main/third_party/python/requirements.txt' _main/third_party/python/requirements_lock.txt //third_party/python:requirements.update '--resolver=backtracking' --allow-unsafe --generate-hashes '--requirements-windows=_main/third_party/python/requirements_windows.txt' --strip-extras
Updating third_party/python/requirements_windows.txt
Error: Could not open file 'third_party/python/requirements_windows.txt': No such file or directory
```

After:
```sh
bazel run //third_party/python:requirements.update
INFO: Invocation ID: 39f999a0-6c1d-4b2c-a1be-3d71e838916a
INFO: Analyzed target //third_party/python:requirements.update (5 packages loaded, 45 targets configured).
INFO: Found 1 target...
Target //third_party/python:requirements.update up-to-date:
  bazel-bin/third_party/python/requirements.update.zip
  bazel-bin/third_party/python/requirements.update.exe
INFO: Elapsed time: 5.410s, Critical Path: 4.79s
INFO: 2 processes: 1 internal, 1 local.
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/third_party/python/requirements.update.exe '--src=_main/third_party/python/requirements.txt' _main/third_party/python/requirements_lock.txt //third_party/python:requirements.update '--resolver=backtracking' --allow-unsafe --generate-hashes '--requirements-windows=_main/third_party/python/requirements_windows.txt' --strip-extras
Updating third_party/python/requirements_windows.txt
#
# This file is autogenerated by pip-compile with Python 3.13
# by the following command:
#
#    bazel run //third_party/python:requirements.update
#
mpmath==1.3.0 \
    --hash=sha256:7a28eb2a9774d00c7bc92411c19a89209d5da7c4c9a9e227be8330a23a25b91f \
    --hash=sha256:a0b2b9fe80bbcd81a6647ff13108738cfb482d481d826cc0e02f5b35e5c88d2c
    # via sympy
sympy==1.13.3 \
    --hash=sha256:54612cf55a62755ee71824ce692986f23c88ffa77207b30c1368eda4a7060f73 \
    --hash=sha256:b27fd2c6530e0ab39e275fc9b683895367e51d5da91baa8d3d64db2565fec4d9
    # via -r G:/projects/bedrock-engine/third_party/python/requirements.txt
```
And `//third_part/python:requirements_windows.txt` is updated.

Fixes #1943 
Fixes #1431

### CODE REVIEW

**Comment by aignas** [comment]
Thanks for the PR.
* Could you please add documentation as part of this PR to the https://github.com/bazelbuild/rules_python/blob/main/docs/pypi-dependencies.md file to explicitly state what the minimum requirements for Windows are? Do we still require these options?
* Maybe it would be a good idea to change the `.bazelrc` in the examples to drop the options to ensure that we are testing the Windows part in the CI? What do you think?

**Comment by ChewyGumball** [comment]
>     * Could you please add documentation as part of this PR to the https://github.com/bazelbuild/rules_python/blob/main/docs/pypi-dependencies.md file to explicitly state what the minimum requirements for Windows are? Do we still require these options?

There are no longer any minimum requirements on Windows after this PR. I don't see any such existing requirements in that document, so I don't think we need to add anything do we?

>     * Maybe it would be a good idea to change the `.bazelrc` in the examples to drop the options to ensure that we are testing the Windows part in the CI? What do you think?

The problem is that the test created by `compile_pip_requirements` doesn't update the file in the source tree, so the existing integration tests can't cover this issue. I don't know how to make a test that would cover this issue because we would need to run the `compile_pip_requirements.update` target, and I don't think you can run a target from a test.

**Review by aignas — COMMENTED** [review]
I'll play with the CI a little later, for now I wanted to leave the comment on the documentation.

**Review by aignas — APPROVED** [review]
I'll leave this as is for now as I would love to merge this fix to improve Windows support.

**Pull request merged**
