### PR TITLE
Added targets for data and dist-info to pip generated targets

### PR DESCRIPTION
**Pull request by UebelAndre**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Does not include precompiled binaries, eg. `.par` files. See [CONTRIBUTING.md](https://github.com/bazelbuild/rules_python/blob/master/CONTRIBUTING.md) for info
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

A wheel is [documented](https://www.python.org/dev/peps/pep-0491/#file-contents) to contain both `.dist-info` and `.data` directories which contain additional metadata for a particular package. However, even though the pip repository rules extract wheel contents into the repository directory, data in these directories are not exposed. In order to access this, the `:whl` target must be consumed and unzipped again, even though this information already lives in the pip repository generated by Bazel. Something should be done to expose this data so users don't have to write additional parsers.

Issue Number: N/A

## What is the new behavior?

This pull request exposes files in `.data` and `.dist-info` in individual filegroups, allowing users to consume them without having to re-extract this data from the wheel.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by caseyduquettesc — APPROVED** [review]
LGTM

**Review by alexeagle — APPROVED** [review]
Thanks!

I wish there was a test for this, if you have some time could you add one in a followup? I'm not sure where to look for one (maybe the examples/pip_install could do something with the dist_info or data from boto3?)

**Comment by UebelAndre** [comment]
> Thanks!
> 
> I wish there was a test for this, if you have some time could you add one in a followup? I'm not sure where to look for one (maybe the examples/pip_install could do something with the dist_info or data from boto3?)

Yeah, I can put together a test when I have a block of free time

**Comment by UebelAndre** [comment]
I've opened https://github.com/bazelbuild/rules_python/pull/524 to add tests.

**Pull request merged**
