### PR TITLE
feat: Create `all_data_requirements` alias

### PR DESCRIPTION
**Pull request by kevinpark1217**
Minor change.

I am creating a Python virtualenv with Bazel, and having `all_data_requirements` for data dependencies just like `all_requirements` would be very helpful.

### CODE REVIEW

**Comment by kevinpark1217** [comment]
Hello @hrfuller @rickeylev, can I get a review?

**Comment by chrislovecnm** [comment]
How can we test this? Can we add something to be of our examples?

**Comment by kevinpark1217** [comment]
> How can we test this? Can we add something to one of our examples?

Hi @chrislovecnm, I added a `build_test()  under `examples/bzlmod`. Also, `examples/pip_parse_vendored/requirements.bzl` shows the generated output.

**Review by chrislovecnm — APPROVED** [review]
LGTM - if you could add some documentation in the examples, that would rock!

**Pull request merged**
