### PR TITLE
refactor: move PyPI related extension and repository_rule setup to its own dir

### PR DESCRIPTION
**Pull request by aignas**
This is to ensure that future work is easier and its clear where to add tests.
Now all of the unit tests can be run by just `bazel test //tests/pypi/...`.

Refactor summary:
- chore: add aignas to CODEOWNERS
- chore: add a new directory for storing PyPI related code
- move pypi_index_sources.bzl to private/pypi
- chore: move parse_requirements_txt to private/pypi
- move parse_whl_name to private/pypi
- move whl_target_platforms to private/pypi
- move parse_requirements to private/pypi
- move pip_repo_name to private/pypi
- remove unused file
- move pip_config_settings to private/pypi
- move pypi_index to pypi/private and rename
- move labels.bzl to private/pypi
- move generate_build_bazel to private/pypi
- move render_pkg_aliases.bzl to private/pypi
- move patch_whl.bzl to private/pypi
- Move envsubst and render_tests to top level of tests
- move pip_install_srcs to private/pypi
- split and move pip_install/pip_repository.bzl to private/pypi
- move the bzlmod extension to private/pypi

### CODE REVIEW

**Comment by aignas** [comment]
This is ready to be reviewed. The main idea was to move all of the code that is
mostly used in the `repository_rule` and `module` context to a single location
so that code reuse would be more ergonomic. It also makes it easier to run
tests when doing refactorings as all of the tests are also collected into a
single place.

FYI @groodt, I haven't moved any of the locking code and I am wondering if we should move it to the same place.

**Comment by groodt** [comment]
> FYI @groodt, I haven't moved any of the locking code and I am wondering if we should move it to the same place.

Yes please! The structure has been driving me dizzy for ages.

**Review by groodt — APPROVED** [review]
LGTM

**Comment by aignas** [comment]
Ducided to do this as a separate PR. Also, because you are spiking thu uv right now, not sure what the structure will be, so just decided to have something merged rather than polishing it too much myself.

My thinking was that the locking stuff could be under private/pypi/lock or private/lock or private/resolve or just plain private/pypi. Let me know what you think.

This weekend I don't have time for the cluanup anymore, so I'll leave this to you or future myself. :)

**Pull request merged**
