### PR TITLE
Update pip, setuptools, wheel, and parse requirements from METADATA

### LINKED ISSUE #126: unable to find pip extras
BUILD
```
load("@preprocessing//:requirements.bzl", "requirement")

py_binary(
    name = "preprocessing",
    main = "preprocess.py",
    srcs = ["preprocess.py"],
    deps = [ 
        "//src/roboflow/pipeline/common:constants",
        requirement("apache-beam[gcp]"),
        requirement("protobuf"),
        requirement("tensorflow"),
    ]   
)
```

requirements.txt

```
apache-beam[gcp]==2.5.0
tensorflow==1.8
protobuf==3.6.1
```
ERROR: /src/workspace/src/roboflow/pipeline/preprocessing/BUILD:3:1: Traceback (most recent call last):
        File "/src/workspace/src/roboflow/pipeline/preprocessing/BUILD", line 3
                py_binary(name = "preprocessing", main = "pr...", <2 more arguments>)
        File "/src/workspace/src/roboflow/pipeline/preprocessing/BUILD", line 9, in py_binary
                requirement("apache-beam[gcp]")
        File "/tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/preprocessing/requirements.bzl", line 498, in requirement
                fail(("Could not find pip-provided de...))
Could not find pip-provided dependency: 'apache-beam[gcp]'

### LINKED ISSUE #253: Update pip version to > 19.0
This is to match [tensorflow's requirement](https://www.tensorflow.org/install#download-a-package).

Current pip version is 9.0.3. (Looks like pip recently switched the versioning scheme to use the last two digits of the year.)

### PR DESCRIPTION
**Pull request by samschlegel**
This updates pip, setuptools, and wheel, and switches to parsing METADATA instead of metadata.json
```
pip==19.3.1
setuptools==42.0.2
wheel==0.33.6
```

Due to changes in https://github.com/pypa/wheel/issues/195, wheel no longer includes a metadata.json, so I've also switched to using `pkg_resources` to parse the package metadata and resolve dependencies and extras. This was most obvious in packages where wheels were built locally, but after making the change it was obvious that this should also fix some metadata related bugs.

As it is currently, this might cause issues with extras for packages that only include the extras in metadata.json, but I wasn't able to find any packages that did this.

Fixes #126, #253, #95, #70, #185

### CODE REVIEW

**Comment by samschlegel** [comment]
Looks like this fails due to missing `googleapis-common-protos[grpc]`
```

(02:10:36) ERROR: /private/var/tmp/_bazel_buildkite/824a4042afe4624418ffa6a61b765b34/external/examples_extras/requirements.bzl:243:5: Traceback (most recent call last):
--
  | File "/Users/buildkite/builds/bk-imacpro-10/bazel/rules-python-python/examples/extras/BUILD", line 21
  | py_test(name = "extras_test", <3 more arguments>)
  | File "/Users/buildkite/builds/bk-imacpro-10/bazel/rules-python-python/examples/extras/BUILD", line 28, in py_test
  | requirement(<1 more arguments>)
  | File "/private/var/tmp/_bazel_buildkite/824a4042afe4624418ffa6a61b765b34/external/examples_extras/requirements.bzl", line 243, in requirement
  | fail(<1 more arguments>)
  | Could not find pip-provided dependency: 'googleapis-common-protos[grpc]'
```

**Comment by samschlegel** [comment]
This looks to be due to the `wheel` version upgrade removing support for `metadata.json` https://github.com/pypa/wheel/issues/195

**Comment by jmcfallargo** [comment]
This PR fixed my issues with Tensorflow and didn't introduce any regressions fwiw.  How do we get a reviewer?

**Comment by kjson** [comment]
Any update on this? This PR fixes several packages for us.

**Comment by gertvdijk** [comment]
How does this pass the test on version check? This PR does not touch the line to assert for Pip version 9.0.3:

https://github.com/bazelbuild/rules_python/blob/38f86fb55b698c51e8510c807489c9f4e047480e/examples/version/version_test.py#L22

yet CI says:

> //examples/version:version_test                                 (cached) PASSED in 0.2s

**Comment by aaliddell** [comment]
Since there seems to be some activity ongoing on this repo again, could one of the PRs be merged that supports METADATA parsing? This fix solves a lot of issues that are persistently raised around rules_python.
@brandjon @lberki

**Comment by ddlees** [comment]
@brandjon @samschlegel

Would you be able to provide some timeline for when you might be able to resolve conflicts / review and merge this PR? I'm content w/ the prescribed workaround but it would be awesome if I didn't have to list out all the transitive deps of a package. Cheers! 🍻

**Comment by samschlegel** [comment]
I've rebased!

**Comment by dayfine** [comment]
So will this be merged? Or am I supposed to use `rules_python_external`?

- I don't (really) want to rely on `dillon-giacoppo/rules_python_external` for a while and then have to switch back
- If `dillon-giacoppo/rules_python_external` is gonna be *the* solution, then `README.md` should be updated.

**Comment by thundergolfer** [comment]
Hey @dayfine, 

I maintain `rules_python_external` (alongside @dillon-giacoppo) and have [recently become a maintainer here](https://github.com/bazelbuild/rules_python/issues/291). 

The relationship between `rules_python` and `rules_python_external` is of immediate concern to the community, but the recently added maintainers need some time build a working relationship and discuss next steps. 

If `rules_python_external` solves an immediate problem you're having, I'd recommend using it. Where it is _the_ solution will be answer ASAP. 

> On a side note, do I still need this...

This change is affecting how the `requirement(X)` targets [get created](https://github.com/bazelbuild/rules_python/pull/263/files#diff-936ee1a7487bf185b90f0d2813ead64dR182), so I think this would affect whether extras work even if your `requirements.txt` is transitively closed.

**Comment by ddlees** [comment]
@thundergolfer Semi-related to this issue is the dependency on the system installed version of python. Regardless of where these rules will be maintained, I put together a small rules project to address that bit of it. (https://github.com/digital-plumbers-union/rules_pyenv)

For this issue, my thought is that bazel controlled versions of python would aid the bits around pip, wheels and setuptools; ensuring those too are hermetic/ bazel controlled. Anyway, I wanted to update this post with that link while I was thinking about it. Maybe you guys will find it useful too! ¯\_(ツ)_/¯

**Pull request closed without merging**
