### PR TITLE
fix(gazelle): empty list

### PR DESCRIPTION
**Pull request by hunshcn**
This is a code error (from typo).

### CODE REVIEW

**Comment by hunshcn** [comment]
Reported by @Whoaa512 .

I didn't modify changelog and test because although I believe this is a mistake, I didn't think of how to trigger this problem.

Did you trigger this error in some scenes? @Whoaa512

**Comment by Whoaa512** [comment]
No, I just noticed because I was referencing at rules_python while building a new language plugin.

**Comment by hunshcn** [comment]
Should I modify changelog? There should be no user-oriented modification.

**Comment by aignas** [comment]
I think no need to change the changelog, FYI @dougthor42.

**Review by dougthor42 — APPROVED** [review]
Agreed, no update to changelog needed.

**Pull request merged**
