### PR TITLE
Fix errors with incompatible_disallow_empty_glob

### PR DESCRIPTION
**Pull request by gergelyfabian**
Allow py_library sources to be empty.
If --incompatible_disallow_empty_glob is set then generated py_library
targets will fail if there are no .py files.

Examples are pymssql==2.1.4 and cx-Oracle==7.2.3.

Set `allow_empty = True` for glob().

Bazel issue for incompatible_disallow_empty_glob:
https://github.com/bazelbuild/bazel/issues/8195

### CODE REVIEW

**Comment by thundergolfer** [comment]
Hey @gergelyfabian, 

The `.par` files are binary files and therefore unreviewable, so for security reasons we will regenerate the .par files for you when merging your pull request. see [CONTRIBUTING.md](https://github.com/bazelbuild/rules_python/blob/master/CONTRIBUTING.md). 

you can remove them from your PR 🙂

**Comment by gergelyfabian** [comment]
Thanks! Will do.

Jonathon Belotti <notifications@github.com> ezt írta (időpont: 2020. máj.
21., Cs 4:41):

**Comment by gergelyfabian** [comment]
> Thanks! Will do.

I have removed the .par files.

**Comment by gergelyfabian** [comment]
Just a comment: rules_python_external is not experiencing this problem, because it adds a `__init__.py` file to the generated Bazel structure:

rules_python_external (for pymssql):

```
.
├── BUILD
├── _mssql.cpython-36m-x86_64-linux-gnu.so
├── pymssql-2.1.4.dist-info
│   ├── __init__.py
│   ├── METADATA
│   ├── RECORD
│   ├── top_level.txt
│   └── WHEEL
└── pymssql.cpython-36m-x86_64-linux-gnu.so
```

While rules_python does (for pymssql):

```
.
├── BUILD
├── _mssql.cpython-36m-x86_64-linux-gnu.so
├── pymssql-2.1.4.dist-info
│   ├── METADATA
│   ├── RECORD
│   ├── top_level.txt
│   └── WHEEL
├── pymssql.cpython-36m-x86_64-linux-gnu.so
└── WORKSPACE
```

So maybe the fix should be to add the `__init__.py` file creation, rather then to add `allow_empty = True`?

**Comment by gergelyfabian** [comment]
Answering my own question on `__init__.py`. In rules_python_external the decision was made, that it should not depend on some generated code (done by the plugin), but rather allow for no Python sources if this is e.g. a pip package implemented in Cython (that means no Python sources in Bazel cache for that).

So I'd argument that the fix should be to add allow_empty = True.

**Comment by thundergolfer** [comment]
@gergelyfabian I think this change would be good to merge with a comment about which scenarios produce packages without py srcs. Like was done here -> https://github.com/dillon-giacoppo/rules_python_external/pull/40/files 👍

**Comment by gergelyfabian** [comment]
@thundergolfer I've updated the PR.

**Pull request merged**
