### PR TITLE
chore: Bump rules_testing to 0.4.0 from 0.0.5

### PR DESCRIPTION
**Pull request by rickeylev**
This uses the 0.4.0 release of rules_python, which has several features we can make use of
 * Various internal APIs have been made public
 * target_compatible_with can be set to skip tests by platform
 * Unit tests are easier to write

Also adds rules_license 0.0.7, which is a dependency of rules_testing.

Work towards #1297

### CODE REVIEW

**Comment by rickeylev** [comment]
fyi @aignas this version of rules testing has the helpers that make writing unit tests easier

**Comment by aignas** [comment]
Yeah, I bumped it in #1294 already, but I am happy to rebase/merge in once this is merged.

**Comment by aignas** [comment]
I've found that I needed to also add `rules_licence` into the `internal_deps.bzl` to get it to work. I was having the following issue:
```
ERROR: /private/var/tmp/_bazel_ignas.anikevicius/4dee77d851edd2d6539c56c842f51cfb/external/rules_testing/BUILD:26:8: @rules_testing//:package_license: missing value for mandatory attribute 'license_kinds' in '_license' rule
ERROR: /private/var/tmp/_bazel_ignas.anikevicius/4dee77d851edd2d6539c56c842f51cfb/external/rules_testing/lib/BUILD:110:11: every rule of type do_nothing implicitly depends upon the target '@rules_testing//:package_license', but this target could not be found because of: Target '@rules_testing//:package_license' contains an error and its package is in error
ERROR: Analysis of target '//tests/pip_hub_repository/entry_point:template_is_interpolated_correctly' failed; build aborted:
INFO: Elapsed time: 9.603s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 131 targets configured)
ERROR: Couldn't start the build. Unable to run tests
```

**Comment by chrislovecnm** [comment]
> I've found that I needed to also add `rules_licence` into the `internal_deps.bzl` to get it to work. I was having the following issue:
> 
> ```
> ERROR: /private/var/tmp/_bazel_ignas.anikevicius/4dee77d851edd2d6539c56c842f51cfb/external/rules_testing/BUILD:26:8: @rules_testing//:package_license: missing value for mandatory attribute 'license_kinds' in '_license' rule
> ERROR: /private/var/tmp/_bazel_ignas.anikevicius/4dee77d851edd2d6539c56c842f51cfb/external/rules_testing/lib/BUILD:110:11: every rule of type do_nothing implicitly depends upon the target '@rules_testing//:package_license', but this target could not be found because of: Target '@rules_testing//:package_license' contains an error and its package is in error
> ERROR: Analysis of target '//tests/pip_hub_repository/entry_point:template_is_interpolated_correctly' failed; build aborted:
> INFO: Elapsed time: 9.603s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (11 packages loaded, 131 targets configured)
> ERROR: Couldn't start the build. Unable to run tests
> ```

Does this PR need to do that?

**Comment by rickeylev** [comment]
> Does this PR need to upgrade rules_license

Not strictly, no. I think what's happening is the parts of rules_testing Ignas is using end up pulling in rules_license, while the parts we're currently using don't. CI is happy and all the existing rules_testing tests pass.

But sure, I can also add rules_license in this PR. Done.

**Comment by chrislovecnm** [comment]
@rickeylev CI is being cranky

**Comment by rickeylev** [comment]
Flakes, all good now.

**Review by chrislovecnm — APPROVED** [review]
LGTM

**Pull request merged**
