### PR TITLE
pip: 22.0.4 -> 22.1.2; pip-tools: 6.6.0 -> 6.6.2

### PR DESCRIPTION
**Pull request by groodt**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Upgrades pip and pip-tools to the latest versions.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
Did we ever figure out why the last time we bumped these, it affected users applications? We are in the same namespace that user pip installs go in?

**Comment by phlax** [comment]
> Did we ever figure out why the last time we bumped these, it affected users applications?

`pip-tools` changed how it handles namespaced packages - `-` is used for `.` in package names - im guessing this is the issue you are referring to

**Comment by groodt** [comment]
> Did we ever figure out why the last time we bumped these, it affected users applications?

My issues were caused by the bump of `pkginfo` https://github.com/bazelbuild/rules_python/issues/671 and was fixed when we removed that dependency here https://github.com/bazelbuild/rules_python/pull/700

**Comment by alexeagle** [comment]
Cool thanks for tracking that down

**Pull request merged**
