### PR TITLE
runfiles: Import `CurrentRepository` from Bazel

### PR DESCRIPTION
**Pull request by fmeum**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

The runfiles library is not able to determine the canonical name of a repo that uses `Rlocation` and thus can't look up the corresponding entries in the repository mapping manifest created by Bazel.

## What is the new behavior?

Upstreams the `CurrentRepository` function from the Bazel version of the runfiles library. This function will be used in a follow-up change to make `Rlocation` aware of repository mapping.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by fmeum** [comment]
CC @alexeagle 

This has the same CI failure as https://github.com/bazelbuild/rules_python/pull/987 that I don't yet know how to solve.

**Review by rickeylev — COMMENTED** [review]
LGTM for the runfiles.py changes.

**Comment by rickeylev** [comment]
I don't fully understand the CI error either, so I'm not sure I can help much there...

The only thing about it that sticks out to me is it reports `//examples/bzlmod/runfiles:runfiles_test` as the target that failed. But wouldn't that imply it's using the root-level WORKSPACE file, when it should be using the `examples/bzlmod/{WORKSPACE,MODULE}` files instead?

**Comment by fmeum** [comment]
@rickeylev The update script under `tools/bazel_integration_test` ended up breaking the build as it deletes the `//examples/wheel` package which is referenced by regular tests. Manually editing the deletes packages lost fixed the problem.

**Comment by fmeum** [comment]
@alexeagle Let me know if you want me to fix the script that updates `--delete_package`, but I would probably just hardcode an exclude list.

**Comment by alexeagle** [comment]
Yeah someone broke that script, and I haven't had time to investigate. Sorry that wasted your time. I suppose we could remove it and force everyone to keep the list manually curated, if no one has time to fix it.

**Review by alexeagle — APPROVED** [review]
very nice thanks!

**Pull request merged**
