### PR TITLE
fix(coverage) add coverage support for python 3.12

### PR DESCRIPTION
**Pull request by trentontrees**
Summary:    
* chore(coverage): bump coverage to 7.4.1
* style: update comments on how to update coverage
* fix(coverage): add cp312 support

### CODE REVIEW

**Comment by trentontrees** [comment]
I've not figured out how to use my local instance of rules_python to verify the changes are working as expected.

**Comment by aignas** [comment]
The bzlmod example is failing when it is just trying to run bazel coverage and it seems that tho patch that we apply to the wheel may need revising. I think just doing bazel fetch for all of the coverage deps whilst in the rules_python workspace should be enough to test this. Maybe adding a skylib build_test to do that in tests/coverage/BUILD.bazel or similar would be good.

**Comment by trentontrees** [comment]
If I am working on `main` without any modifications:

cd /examples/bzlmod
bazel coverage //...
# 8 fail locally

**Comment by trentontrees** [comment]
Note that #1734 should be merged before this PR.

**Review by aignas — APPROVED** [review]
LGTM

**Comment by trentontrees** [comment]
@aignas this PR is ready for merge as well.  Thank you!

**Review by aignas — APPROVED** [review]

**Pull request merged**
