### PR TITLE
chore: bump internal_deps

### LINKED ISSUE #1351: Shipped version of importlib_metadata incompatible with pip_tools
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: 
rules_python (module and workspace variant)

### Is this a regression?
Yes, the I don't recall the exact version of rules_python that this didn't appear in, but the bug was introduced here https://github.com/bazelbuild/rules_python/pull/781

### Description
[Original slack thread](https://bazelbuild.slack.com/archives/CA306CEV6/p1689733658811589).

When attempting to upgrade `rules_python` I kept running into the following error.
```python
AttributeError: 'PathDistribution' object has no attribute 'name'
```
This error was raised when anything attempts to resolve a pypi dependency. I explored using different parts of the rules_python api, but the only solution has been to bump `importlib_metadata`.

## 🔬 Minimal Reproduction

My module file
```starlark
bazel_dep(name = "rules_python", version = "0.24.0")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pip",
    requirements_lock = "//:requirements.txt",
)
use_repo(pip, "pip")
```

Build file. Both requirements files are empty (got the same result when they werent).
```starlark
compile_pip_requirements(
    name = "requirements",
    extra_args = [
        "--allow-unsafe",
        "--resolver=backtracking",
    ],
    requirements_in = "requirements.in",
    requirements_txt = "requirements.txt",
)
```

## 🔥 Exception or Error
<pre><code>
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:requirements_test
-----------------------------------------------------------------------------
['/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0/python/pip_install/tools/dependency_resolver/dependency_resolver.py', '--generate-hashes', '--allow-unsafe', '--resolver=backtracking', '--cache-dir', '/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/_tmp/24e3066da9cc133a367098d5abc917e6', '--output-file', '/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/_tmp/24e3066da9cc133a367098d5abc917e6/requirements.txt.out', 'requirements.in']
Checking _main/requirements.txt
Traceback (most recent call last):
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0/python/pip_install/tools/dependency_resolver/dependency_resolver.py", line 188, in <module>
    cli()
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__click/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__click/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__click/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__click/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__click/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip_tools/piptools/scripts/compile.py", line 421, in cli
    repository = PyPIRepository(pip_args, cache_dir=cache_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip_tools/piptools/repositories/pypi.py", line 75, in __init__
    self._session = self.command._build_session(options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
    matches = (
              ^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/metadata/importlib/_envs.py", line 175, in _iter_distributions
    yield from finder.find(location)
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/metadata/importlib/_envs.py", line 79, in find
    for dist, info_location in self._find_impl(location):
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl
    raw_name = get_dist_name(dist)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.cache/bazel/_bazel_<user>/0a2a8470bd48485f12b59e4a2004868a/execroot/_main/bazel-out/k8-fastbuild/bin/requirements_test.runfiles/rules_python~0.24.0~internal_deps~pypi__pip/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name
    name = cast(Any, dist).name
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PathDistribution' object has no attribute 'name'
</code></pre>

## 🌍  Your Environment

**Operating System:**

```shell
uname -srm
Linux 6.4.6-200.fc38.x86_64 x86_64
```

**Output of `bazel version`:**

```shell
bazel version
Bazelisk version: development
Build label: 6.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 2 16:59:58 2023 (1685725198)
Build timestamp: 1685725198
Build timestamp as int: 1685725198
```
**Rules_python version:**

```l
0.24.0
```
**Anything else relevant?**

I bisected the different pre-built wheels of `imputlib_metadata` to determine which version has the property being looked for the the above error, and the first version that is compatible is 3.3.0. 

This resolves the above error and pip works as expected.
```diff
diff --git a/python/pip_install/repositories.bzl b/python/pip_install/repositories.bzl
index efe3bc7..e462fae 100644
--- a/python/pip_install/repositories.bzl
+++ b/python/pip_install/repositories.bzl
@@ -77,8 +77,8 @@ _RULE_DEPS = [
     ),
     (
         "pypi__importlib_metadata",
-        "https://files.pythonhosted.org/packages/d7/31/74dcb59a601b95fce3b0334e8fc9db758f78e43075f22aeb3677dfb19f4c/importlib_metadata-1.4.0-py2.py3-none-any.whl",
-        "bdd9b7c397c273bcc9a11d6629a38487cd07154fa255a467bf704cd2c258e359",
+        "https://files.pythonhosted.org/packages/7a/85/ac225e35048e050a6351b6f1251cdb2b6060092f2c6840aff1d6319941b1/importlib_metadata-3.3.0-py3-none-any.whl",
+        "bf792d480abbd5eda85794e4afb09dd538393f7d6e6ffef6e9f03d2014cf9450",
     ),
     (
         "pypi__zipp",
```

### PR DESCRIPTION
**Pull request by aignas**
Before this PR the dependencies were out of date and the `pyproject_hooks` was
missing allowing `pip-compile` to use `pyproject.toml` instead of
`requirements.in`. With the update we are more likely to support the new
features but they are not tested in this PR as the main goal is to update all of
the files that need regenerating due to upgraded `pip-tools`.

Here we:
* Upgrade all of the deps to the latest versions.
* Update all of the requirements and gazelle manifest files.
* Add a quirk to ensure fix `pip_compile` on Windows.

Summary of version changes:
* build: 0.9.0 -> 0.10.0
* click: 8.0.1 -> 8.1.6
* importlib_metadata: 1.4.0 -> 6.8.0
* more_itertools: 8.13.0 -> 10.1.0
* packaging: 22.0 -> 23.1
* pip: 22.3.1 -> 23.2.1
* pip_tools: 6.12.1 -> 7.2.0
* pyproject_hooks: 1.0.0
* setuptools: 60.10.0 -> 68.0.0
* wheel: 0.38.4 -> 0.41.0
* zipp: 1.0.0 -> 3.16.2

Fixes #1351

### CODE REVIEW

**Comment by aignas** [comment]
This is still failing on Windows, but I am not entirely sure why, maybe someone with Windows could look deeper in to this.

**Comment by rickeylev** [comment]
The windows error is:
```
      File "C:\temp\Bazel.runfiles_nst1tke9\runfiles\python39_x86_64-pc-windows-msvc\lib\pathlib.py", line 276, in gethomedir
        raise RuntimeError("Can't determine home directory")
    RuntimeError: Can't determine home directory
```

It's originating via pip -> setuptools -> pathlib. As part of, what appears to be, looking for configuration files. Perhaps there's an issue filed upstream? Is this setuptools version compatible with Python 3.9?

Looking at the Python 3.9 pathlib code, it checks for USERPROFILE in the environment, which _is_ set. Maybe that isn't filtering down to the the action? Adding --test_env=USERPROFILE in the CI config might fix that.

**Comment by chrislovecnm** [comment]
> It's originating via pip -> setuptools -> pathlib. As part of, what appears to be, looking for configuration files. Perhaps there's an issue filed upstream? Is this setuptools version compatible with Python 3.9?

I'm not finding an issue upstream in setuptools.  And I cannot find a compatibility matrix.

**Comment by chrislovecnm** [comment]
So adding the parameter `--no-user-cfg` will bypass this code.

https://github.com/pypa/setuptools/blob/1d9420746741c6ad8bc0757b5dcf6cadf3c1444d/setuptools/_distutils/dist.py#L279

I don't think we want to pick up user configuration anyways.

There are long discussions around '~,' and Windows https://github.com/python/cpython/issues/80445 is one of them.

**Comment by aignas** [comment]
I spent some time debugging this and trying to understand the root cause of what is going on and I am not sure that the previous analysis in the comment above is entirely correct.

Looking at [this log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/018a279d-6523-4cf6-a319-9142fca06d6a/requirements_test%5Ctest_attempts%5Cattempt_1.log), I think what is happening is the following:
1. The `pip-tools` is trying to lock the requirements.
1. Then it is calling `pip` internal to fully resolve everything.
1. Then `pip` needs to do some processing of the package and it is calling the *vendored* `pyproject-hooks` which exists within the `pip/_vendor` folder.
1. ...
1. It calls a `subprocess.run` which due to some reason has it's `sys.path` include Python files from outside the `runfiles` directory:
   ```
   C:\temp\Bazel.runfiles_n6t3rqoq\runfiles\pypi__pip\pip\_vendor\pyproject_hooks\_in_process
   C:\temp\pip-build-env-gejvde8f\site
   C:\temp\Bazel.runfiles_n6t3rqoq\runfiles\python39_x86_64-pc-windows-msvc\python39.zip
   C:\temp\Bazel.runfiles_n6t3rqoq\runfiles\python39_x86_64-pc-windows-msvc\DLLs
   C:\temp\Bazel.runfiles_n6t3rqoq\runfiles\python39_x86_64-pc-windows-msvc\lib
   C:\temp\pip-build-env-gejvde8f\overlay\Lib\site-packages
   C:\temp\pip-build-env-gejvde8f\normal\Lib\site-packages
   ```
1. We fail whilst we are trying to build a wheel? This is where I get confused,
   as locking down the requirements should not need to build them, but given
   Python packaging complexity and non-hermeticity I would not be surprised if
   this is the actual behaviour that we have here.

I still think it would be good to get to the root cause of this and have the
full picture why `multi_versions`, `pip_install` and `pip_parse` integration
tests. `multi_versions` example is also only failing with Python `3.11`,
whereas other examples are using `3.9`. What is more, `multi_versions`
requirements contain only websockets and I am curious why it would work with
one Python version but not others. The same goes for why it would work on Linux
but not on Windows.

**Comment by groodt** [comment]
> 6\. We fail whilst we are trying to build a wheel? This is where I get confused,
>     as locking down the requirements should not need to build them, but given
>     Python packaging complexity and non-hermeticity I would not be surprised if
>     this is the actual behaviour that we have here.

Oh, yes, this is precisely what happens when locking dependencies. This happens automatically when an sdist is encountered, because there is no static metadata for sdists. So a wheel is built from the sdist. If I had my way, the rules would only support wheels (`--only-binary=:all:`), but I think that ship sailed long ago.

The test is failing on `yamllint` which is only provided as an sdist (https://pypi.org/project/yamllint/#files). Why does the test require yamllint? Can't we do something else instead?

I personally think this might be too aggressive an upgrade? What's the motivation to upgrade everything at once? If we're upgrading the tooling dependencies, such as pip-tools and build, I can get behind that. 

In general, upgrading `setuptools` needs to be done carefully, because we probably want the oldest version of `setuptools` thats compatible with `pip` and the rest of our tools? If we upgrade `setuptools` too aggressively, we risk breaking the ability to build older packages? From my quick skim of the upgrade, I don't see anything obvious, but setuptools is a load-bearing, so unless there's a strong reason to upgrade it, maybe upgrade it independently?

**Comment by groodt** [comment]
I think the failure on Windows now, is due to the newer `setuptools` vendored distutils that is attempting to expand a home directory when building an `sdist` for `websocket` on py311 for the old version of `websocket`. 

I can bump the pinned version of `websocket` so that an `sdist` will not be but I think this will likely break rules_python for windows users who have any sdist that make use of distutils?

**Review by f0rmiga — APPROVED** [review]

**Pull request merged**
