### PR TITLE
Implement missing METADATA parsing via pkginfo

### PR DESCRIPTION
**Pull request by mdvorsky**
Replaces the incomplete METADATA parsing with pkginfo. Adds tests using real-world packages.

Fixes https://github.com/bazelbuild/rules_python/issues/102

### CODE REVIEW

**Comment by rogerhub** [comment]
@brandjon Can you take a look? I think this patch is an important fix.

**Comment by mdvorsky** [comment]
@brandjon @lberki any thoughts at all? I realize my fix may not be the preferred way to address this, but I'd love to see this addressed one way or another, so that we can get rid of our local fork of `rules_python`.

**Comment by cristifalcas** [comment]
Hi @brandjon. Please let us know if this project is maintained, or we should move to something else. There are multiple PRs and issues that are not answered for months.

Importing pip packages doesn't work, using python3 is even in a worst state.

**Comment by cgordoncarroll** [comment]
Any updates on this pull request? Using Bazel in conjunction with python3/pip seems pretty painful without this. @brandjon

**Comment by ppodolsky** [comment]
I second @cgordoncarroll. Is there a way we could help to push this PR forward?

**Comment by smamessier** [comment]
Would be very interested in this being merged as well. Trying to use Bazel with Python3 deps.

**Comment by thundergolfer** [comment]
@smamessier 

Have you tried any of these? 

* https://github.com/dillon-giacoppo/rules_python_external
* https://github.com/soniaai/rules_poetry
* https://github.com/ali5h/rules_pip

They all support Python 3. We are using the 1st with Python 3.6 at work. It was created after `bazelbuild/rules_python` just wouldn't work for us.

**Comment by smamessier** [comment]
@thundergolfer Thanks I ended up using https://github.com/dillon-giacoppo/rules_python_external and it works perfectly.

**Comment by mdvorsky** [comment]
@googlebot I fixed it.

**Comment by jakebiesinger-onduo** [comment]
👋  1-year anniversary for this PR is coming up. Any chance we could get it merged?

**Comment by mdvorsky** [comment]
Thanks a lot @andyscott! Would you like me to do anything else here? (The build of your merge failed because of an unrelated issue already fixed at head, afaict).

**Comment by mdvorsky** [comment]
Hi! @thundergolfer @andyscott I removed the .par files from the PR, and squashed the commits. Is there anything else I should do here? Thank you!

**Comment by horkyada** [comment]
Hi `rules_python` folks. Is there any chance this gets merged?

**Comment by xhuoroku** [comment]
@mdvorsky Thank you for the great work!

Is it possible to also make the code change for pip_import so that [issue 102](https://github.com/bazelbuild/rules_python/issues/102) can be fixed when using pip_import? 

It's the only packaging rule that supports Python 2, would be super helpful if it can be fixed.

**Pull request closed without merging**
