### PR TITLE
Fixed glob includes for ignore_root_user_error

### PR DESCRIPTION
**Pull request by linzhp**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

#907 put the comments as elements in the include list of the glob when `ignore_root_user_error` is True, causing test build failures

## What is the new behavior?
Make comments as comments

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
@illicitonion Are you sure you want to put .pyc files in the includes? The description of #907 indicates that you wanted to exclude them, but you ended up including them.

### CODE REVIEW

**Comment by illicitonion** [comment]
Oops, you're correct, I messed that up when resolving a merge conflict - thanks for the heads up! Fixed in https://github.com/bazelbuild/rules_python/pull/1038

**Comment by linzhp** [comment]
Superseded by #1038

**Comment by linzhp** [comment]
Part of this PR has been superseded by #1038, but I still want to keep the tests to cover the case of `ignore_root_user_error = True` to prevent future regression.

**Review by f0rmiga — COMMENTED** [review]
Could you just add a README to the test explaining why the test exists?

**Review by f0rmiga — APPROVED** [review]

**Pull request merged**
