### PR TITLE
fix(rules): remove rules_python --incompatible_python_disallow_native_rules checking

### PR DESCRIPTION
**Pull request by rickeylev**
When --incompatible_python_disallow_native_rules is enabled, all the core rules fail with
an error that rules_python should be used. This is incorrect, since the rules_python rules
are being used. What's happening is https://github.com/bazelbuild/rules_python/pull/2257
removed the magic migration tag when pystar is enabled, but the code to check the tag
was present wasn't removed. This went unnoticed because our CI doesn't set the migration
flag.

To fix, remove the validation logic entirely. If we're in the rules_python implementation,
then there is not need to perform this validation. It was just something copy/pasted from
the original code from Bazel itself.

Also update the bazelrc to always set --incompatible_python_disallow_native_rules.

Fixes https://github.com/bazelbuild/rules_python/issues/2326
Fixes https://github.com/bazelbuild/rules_python/issues/1645

### CODE REVIEW

**Comment by aignas** [comment]
Should we also close #1645 since we would be testing this?

**Review by aignas — APPROVED** [review]

**Comment by aignas** [comment]
This also needs a changelog item.

**Comment by rickeylev** [comment]
> also fix 1645

Hrm. Bazel 6 doesn't have the flag, so setting it in the bazelrc files is problematic. I think what I'll have to do is set it as part of the CI config. I'll give that a try, but I might drop this from the PR if it ends up being a big pain.

> needs changelog entry

Done

**Comment by rickeylev** [comment]
Figure out a way to get th bazelrcs updated. I changed CI to set `--config=bazel7.x` for Bazel 7 builds, and the bazelrcs have `common:bazel7.x` lines with the necessary flags.

**Pull request merged**
