### PR TITLE
Fail if Python 2 values are specified

### PR DESCRIPTION
**Pull request by rickeylev**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Python 2 usages of the rules will immediately fail. Examples include:

```
py_binary(..., python_version="PY2")
py_library(..., srcs_version="PY2")
py_runtime_pair(..., py2_runtime="//something")
```

### CODE REVIEW

**Review by groodt — APPROVED** [review]
LGTM

**Comment by f0rmiga** [comment]
@rickeylev could you resolve the conflicts, please? I'd like to merge this for the next minor release.

**Comment by rickeylev** [comment]
Well, I had intended to merge in January as part of the new year, but...Yeah, lets just do it now. Worst case we find out sooner and can just revert it.

**Comment by f0rmiga** [comment]
All good if you want to wait a bit more.

**Pull request merged**
