### PR TITLE
Switch from using .par files to pure python for piptool and whltool

### PR DESCRIPTION
**Pull request by duggelz**
Addresses #67 

This vendors several third_party packages, which increases the repository size by 12MB and 116000 lines.  Deleting the .par files will get about 6MB of that back.

The .par files will be removed in a separate change.

This change was tested against the rules_k8s repository, and various manual testing.

Alternatives to this change are:
1) Do nothing, continue with the current process
2) Create an actual release process for the .par files, which builds and stores them in a separate repository along with the .bzl files.

### CODE REVIEW

**Comment by duggelz** [comment]
@mattmoor for your consideration

**Comment by duggelz** [comment]
I suggest using GitHub's "Show changes from commit range..." feature, and skip the ginormous third_party commits.

**Comment by c4urself** [comment]
I'd love to see this get in, debugging issues with the PAR files is not fun!!

**Comment by sitaktif** [comment]
Can we do this instead? https://github.com/soniaai/rules_poetry/blob/master/rules_poetry/defs.bzl#L3-L61

**Comment by thundergolfer** [comment]
Closing as release 0.1.0 included a packaging rules implementation that no longer relied on `.par` files.

**Pull request closed without merging**
