### PR TITLE
Fix false positive tests in CI for Windows

### PR DESCRIPTION
**Pull request by jheaff1**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
The error code of the invocation of "bazel shutdown" was queried to
ascertain the result of "bazel test". 

Issue Number: #585

## What is the new behavior?
Now, if the invocation of any
bazel command fails, the test_runner.py script will return code 3.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by jheaff1** [comment]
It seems that `colorama` is present in a requirements.lock file on Windows but not on Linux or MacOS. :(

**Comment by UebelAndre** [comment]
I think the solution here is to find a replacement for `sphinx`. The dependencies used should use all the same requirements on all platforms or we'd need to implement https://github.com/bazelbuild/rules_python/issues/260

**Comment by UebelAndre** [comment]
@jheaff1 I picked up these changes in https://github.com/bazelbuild/rules_python/pull/598 in case you wanted to collaborate there.

**Comment by f0rmiga** [comment]
Addressed in https://github.com/bazelbuild/rules_python/pull/598 and https://github.com/bazelbuild/rules_python/pull/595.

**Pull request closed without merging**
