### PR TITLE
Use "shared" msvc hermetic toolchain

### PR DESCRIPTION
**Pull request by jheaff1**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Using python packages with C modules, e.g. numpy, would fail when using
the "static" toolchain. See 
Issue Number: indygreg/python-build-standalone#124

## What is the new behavior?
When using the "shared" toolchain, importing numpy is successful

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jheaff1** [comment]
The build failure is due to the ` //:examples/wheel:filename_escaping` target. If I run ` bazel build -s //:examples/wheel:filename_escaping` to print out the command that is actually run, and then run said command, it seems to run successfully on this new branch but not on main, which is odd

**Comment by f0rmiga** [comment]
> The build failure is due to the ` //:examples/wheel:filename_escaping` target. If I run ` bazel build -s //:examples/wheel:filename_escaping` to print out the command that is actually run, and then run said command, it seems to run successfully on this new branch but not on main, which is odd

Are you referring to the build failure on CI?

**Comment by jheaff1** [comment]
> > The build failure is due to the ` //:examples/wheel:filename_escaping` target. If I run ` bazel build -s //:examples/wheel:filename_escaping` to print out the command that is actually run, and then run said command, it seems to run successfully on this new branch but not on main, which is odd
> 
> Are you referring to the build failure on CI?

Yes

**Comment by UebelAndre** [comment]
@jheaff1 @f0rmiga Howdy folks! Any updates here?

**Comment by jheaff1** [comment]
> @jheaff1 @f0rmiga Howdy folks! Any updates here?

Hey there! I’m on holiday at the moment so don’t have the time to look into this sadly. It might be a few more weeks before I can take a look

**Comment by phlax** [comment]
we are hitting similar problems to the ones resolved here trying to make use of the hermetic toolchain on windows.

the error we are receiving when trying to make use of an egg that requires compilation is:

```console
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

but afaict we do have c++ build tools in the env (ref https://github.com/envoyproxy/envoy/pull/20432#issuecomment-1129747148) so  im guessing this is an issue related to using the static standalone binary

i tested using this PR - sadly it didnt work at all (afaict some kind of file not found issue - perhaps the expected shared libs - struggling to get useful info out of our win CI)

**Comment by jheaff1** [comment]
> @jheaff1 @f0rmiga Howdy folks! Any updates here?

CI now passes

**Comment by jheaff1** [comment]
> we are hitting similar problems to the ones resolved here trying to make use of the hermetic toolchain on windows.
> 
> the error we are receiving when trying to make use of an egg that requires compilation is:
> 
> ```
>   error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> ```
> 
> but afaict we do have c++ build tools in the env (ref [envoyproxy/envoy#20432 (comment)](https://github.com/envoyproxy/envoy/pull/20432#issuecomment-1129747148)) so im guessing this is an issue related to using the static standalone binary
> 
> i tested using this PR - sadly it didnt work at all (afaict some kind of file not found issue - perhaps the expected shared libs - struggling to get useful info out of our win CI)

To fix the CI build I had to modify the BUILD file for the toolchain repo to include the DLLs provided in the standalone python tarball. Does this updated PR resolve your issue?

**Comment by phlax** [comment]
> Does this updated PR resolve your issue?

not exactly, but it works now

we kinda ~fixed the problem already by upgrading our deps - i guess the "fix" was mostly just not needing to compile

i have tested this branch with/out the "fix" - without it i get the same original error about missing `Visual C++` - im wondering if there is something amiss with our win env.

**Review by f0rmiga — APPROVED** [review]

**Comment by f0rmiga** [comment]
Thanks for fixing this!

**Pull request merged**
